### ISSUE TITLE
Support buildng multiple outputs from a recipe

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/pyodide-build#138]
This feature request is based on a requirement that came up in https://github.com/pyodide/pyodide-build/pull/109 – it would be great if we could also support the conda-forge feature for multiple outputs for builds, which would use the same build environment for building multiple variations of a package.

The proposed implementation could be as follows:
- add an `outputs:` field to the recipe that allows subfields such as `script:`, `about:` `post:`, more `requirements:` (and sub-requirements), etc.
- build in the order they are specified, building the first listed output and proceed to the next one if it passes
    - we can stop if it fails; I don't think we need a --keep-going option or building in parallel at the moment
- the graph builder can keep the same logic, more or less – it's just that one recipe will generate $n$ packages instead of just one

The rationale is that many recipes could benefit from this – for example:
- packages such as NumPy/SciPy/etc. and various Meson-based packages can then use their "install tags" integration with Meson to build WASM wheels for `scipy` and `scipy-tests`, which can be installed together in the same environment. this can be used to control build sizes better than stripping away wheels.
- it allows packages to ship multiple variants of their builds: we could ship NumPy + OpenBLAS and NumPy with Netlib BLAS from the same recipe file, just with different build scripts listed together.
- for libraries: SuiteSparse, for example, can be instructed to build different components separately for packages that need only a specific one.

Reference:
- https://github.com/conda-forge/scipy-feedstock/blob/1e665407f6222093df606d9e27553072b7222fc9/recipe/meta.yaml
- https://github.com/conda-forge/suitesparse-feedstock/blob/d0a371ec49dfb0a9dbbcea5815c0f4c71e87d462/recipe/recipe.yaml

**Comment by ryanking13** [comment]
Thanks for the proposal, @agriyakhetarpal. It sounds like an interesting idea to me. However, I think the format of the `outputs` can be more formalized before we proceed to implementation, for instance, how it will work with the lockfile, etc.

**Comment by agriyakhetarpal** [comment]
Coming back to this from https://github.com/pyodide/pyodide/pull/5563, I think the format will remain largely the same as the current recipes, as we would not like or need the added complexity that comes with conda-forge recipes.

For the lockfile: two outputs would build two different packages with two different names and checksums, which would be placed in the `dist/` folder of the recipe dir, next to `meta.yaml`, so I think we should be fine.

Here is what a sample recipe for NumPy and numpy-tests could look like:

```yaml
package:
  name: numpy
  version: 2.2.3
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  url: https://files.pythonhosted.org/packages/source/n/numpy/numpy-2.2.3.tar.gz
  sha256: dbdc15f0c81611925f382dfa97b3bd0bc2c1ce19d4fe50482cb0ddc12ba30020

outputs:
  - name: numpy
    build:
      unvendor-tests: false # we do this on our own using Meson's install tags
      # numpy uses vendored meson, so we need to pass the cross file manually
      backend-flags: |
        setup-args=-Dallow-noblas=true
        setup-args=--cross-file=${MESON_CROSS_FILE}
        install-args=--tags=runtime,python-runtime,devel
        build-dir=shared_build
      # numpy creates numpy/distutils/__pycache__ directory during the build.
      # It breaks our test because there is a .pyc in the directory.
      post: |
        rm -rf numpy/distutils/__pycache__
      cflags: |
        -Wno-return-type
      cross-build-env: true
      cross-build-files:
        - numpy/_core/include/numpy/numpyconfig.h
        - numpy/_core/include/numpy/_numpyconfig.h
        - numpy/_core/lib/libnpymath.a
        - numpy/random/lib/libnpyrandom.a
  
  - name: numpy-tests
    requirements:
      host:
        - numpy
      run:
        - numpy
    build:
      unvendor-tests: false # we do this on our own using Meson's install tags
      # rename the package before we build
      script: sed -i 's/name = "numpy"/name = "numpy-tests"/' pyproject.toml
      # numpy uses vendored meson, so we need to pass the cross file manually
      # reuse the build directory from the previous output
      backend-flags: |
        setup-args=-Dallow-noblas=true
        setup-args=--cross-file=${MESON_CROSS_FILE}
        install-args=--tags=tests
        build-dir=shared_build
      # numpy creates numpy/distutils/__pycache__ directory during the build.
      # It breaks our test because there is a .pyc in the directory.
      post: |
        rm -rf numpy/distutils/__pycache__
      cflags: |
        -Wno-return-type

about:
  home: https://www.numpy.org
  PyPI: https://pypi.org/project/numpy
  summary: NumPy is the fundamental package for array computing with Python.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - agriyakhetarpal
```

Thus, the difference, and the aspects of this format are as follows:
- NumPy is included in the xbuildenv, but numpy-tests is not
- the `about:` and `extra:` sections are shared for both outputs
- numpy-tests has a build-time dependency and runtime dependency on NumPy. The build-time dependency exists solely to not allow NumPy and numpy-tests to be built together, as we don't want that to happen – we wish to reuse the NumPy build files for numpy-tests, which we marked as persistent using the build-dir config setting.
- all packages listed under `outputs:` are built from the same source directory, and patches, if any, are applied only once
- the outputs are built based on how the graph builder resolves them, and not in order (which also ties into point 3 above).

Of course, this is quite tailored to support this NumPy and numpy-tests scenario, so I think we could keep it Pyodide-maintainer-only and expand it to other packages before we mark it as generally available to all recipe maintainers.

I'm not sure if there are any other implications of this format that we will need to consider, as only an implementation can tell –unless you can foresee some. I have an alternative idea for a persistent/shared build directory that I can put up a PR for in a moment.
