### ISSUE TITLE
Allow lists in `pyodide config`

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/pyodide-build#192]
It would be great if we could support List types in `pyodide_build.config.DEFAULT_CONFIG`. The question is how to support the list type in an env variable.

_Originally posted by @ryanking13 in https://github.com/pyodide/pyodide-build/pull/187#discussion_r2040575604_

**Comment by agriyakhetarpal** [comment]
So, if we do this, it would allow us to use something like:

```toml
[tool.pyodide.build]
ignored_build_requirements = ["patchelf", "oldest-supported-numpy", "cmake", "my-ignored-package"]
```

instead of the current representation where we need to use a single concatenated string.

One thing we could do is to allow lists for configuration variables listed in `pyproject.toml` only, and keep using strings for environment variables, but that introduces a bit of complexity – and I'm sure there are never going to be a lot of cases where a configuration option needs to have multiple values in a list.

N.B. `cibuildwheel` also suffers from the same limitation.
