### ISSUE TITLE
`pyodide skeleton pypi --update` does not completely validate checksums when updating

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/pyodide-build#24]
## Description

The `pyodide skeleton pypi` commands (whether `--update` or `--update-patched`) won't update the hash if they infer the package version is already updated.

## Reproducer

This is a special case where one manually updates the `version:` number for `mypackage` in its recipe and leaves the hash unchanged in the `sha256:` field. In this case, running `pyodide skeleton pypi --update mypackage` will not update the hash, assuming that the user has updated it and validated it themselves. Here's a small example:

<details>
<summary>Click to expand code</summary>

#### `numpy/meta.yaml` (before)

```yaml
package:
  name: numpy
  version: 2.0.1
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  sha256: randomhash12345
```

#### `numpy/meta.yaml` (after a manual bump to the version – 2.1.1 is the latest one available on PyPI at the time of writing)

```yaml
package:
  name: numpy
  version: 2.1.1
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  sha256: randomhash12345
```

Now, if one runs `pyodide skeleton pypi --update numpy`, they get

#### `numpy/meta.yaml` has no change:

```yaml
package:
  name: numpy
  version: 2.1.1
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  sha256: randomhash12345
```

``` bash
❯ pyodide skeleton pypi --update numpy
numpy already up to date. Local: 2.1.1 PyPI: 2.1.1
```

</details>

## Expected behaviour

I think the better pathway would be to assume that a user or recipe maintainer can make mistakes when updating package versions manually, but a computer would not – so, I feel that the command should attempt to update the checksum anyway, even if the version matches the one available on PyPI. This should be the same for `--update` and `--update-patched`.

## Additional information

N/A
